
spring:

  # kafka
  kafka:
    bootstrap-servers: 10.168.1.131:9092
    client-id: joey-test-kafka
    producer:
      acks: 1
      retries: 0
    consumer:
      enable-auto-commit: false

  # es
  elasticsearch:
    uris: http://10.168.1.131:9200


  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://106.55.100.113:3306/sparrow
      username: root
      password: kavier
      maximum-pool-size: 10