
spring:
  application:
    name: canal-adapter-app
  elasticsearch:
    uris: http://192.168.31.118:9200
    username:
    password:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.55.100.113:3306/sparrow
    username: root
    password: kavier

logging:
  level:
    cn.joey.canal.adapter: debug


canal:
  enable: true
  server: # canal server
    host: 106.55.100.113
    zk-servers: 106.55.100.113
    port: 11111
    username: canal
    password: canal
    destination: sparrow
  client: # canal client
    connect-mode: simple
    subscribe: .*\..*
    batch-size: 1024
  adapter:
    rollback-when-exception: false # 批次处理异常时回滚，false则跳过该异常批次，用户需要自己实现额外的数据补偿机制
    thread-pool:
      enable: true
      core-size: 4
      max-size: 6
      queue-capacity: 1
      keep-alive-time: 10000