logging:
  level:
    cn.kavier.canal.adapter: debug

canal:
  enable: true
  server:
    host: 106.55.100.113
    port: 11111
    username: canal
    password: canal
    destination: sparrow
  client:
    connect-mode: simple
    subscribe: .*\..*
    batch-size: 10
  adapter:
    thread-pool:
      enable: false
      core-size: 4
      max-size: 6
      queue-capacity: 1
    filters:
      - key: test1
        table-name: tb_canal_people,tb_canal_animal
        filter:
        es-index-name: xx
        props:
          xxx1: 1112
          xxx2: 2221
      - key: test2
        table-name: tb_canal_animal
        filter: af
        es-index-name: index_canal_animal
        props:
          xxx1: 1112
          xxx2: 2221




canal-adapter:
  enable: true
  connect-mode: simple # cluster
  subscribe: .*\..*
  batch-size: 1
  server:
    host: 106.55.100.113
    port: 11111
    username: canal
    password: canal
    destination: sparrow
  thread-pool:
    enable: false
    core-size: 4
    max-size: 6
    queue-capacity: 1
  es-adapter:
    filters:
    - key: test1
      table-name: tb_canal_people,tb_canal_animal
      filter:
      es-index-name: xx
      props:
        xxx1: 1112
        xxx2: 2221
    - key: test2
      table-name: tb_canal_animal
      filter: af
      es-index-name: index_canal_animal
      props:
        xxx1: 1112
        xxx2: 2221

# todo 下一步是考虑如何配置esindex，然后调整方法处理，将数据改动插入es




# 动态代理配置，需要配置映射






# es相关配置
spring:
  elasticsearch:
    uris: http://192.168.31.118:9200